baseURL = "/"
languageCode = "en"
title = "t3mujinpack"
theme = "hugo-theme-ava"
pagination.pagerSize = 7
mainSections = "post"

[outputs]
  home = ["HTML", "humanstxt", "rss"]
  
  [outputFormats.humanstxt]
      baseName = "humans"
      isPlainText = true
      mediaType = "text/plain"

[services]
  [services.rss]
    limit = 50

[languages]
  [languages.en]
      languageName = "English"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    
[[module.imports]]
    path = "github.com/hugomods/giscus"

[params]
  ga_id=""
  mainSections = ["post"]
  disqus = "xxxxxxx"
  defaultImage = "https://t3mujinpack.github.io/images/banner.jpg"

  [params.meta_tags]
    meta_description = "A pack of presets for open-source RAW developer software Darktable that includes some of the most used photo films of all time, like Velvia or Kodachrome."
    meta_og_title = "t3mujinpack"
    meta_og_sitename = "t3mujinpack, film emulation presets for Darktable"
    meta_og_type = "website"
    meta_og_url = "https://t3mujinpack.github.io"
    meta_og_image = "https://t3mujinpack.github.io/images/banner.jpg"
    meta_og_description = "A pack of presets for open-source RAW developer software Darktable that includes some of the most used photo films of all time, like Velvia or Kodachrome."
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""
    
 [params.humans_txt]
    dev_team = ""
    dev_github = ""
    thanks = ""
    standards = ""
    software = ""
    other_notes = ""
    
[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Releases"
    url = "/releases/"
    weight = 3

[[menu.main]]
    name = "Instructions"
    url = "/instructions/"
    weight = 4

[[menu.main]]
    name = "Updates"
    url = "/posts/"
    weight = 5


[[menu.main]]
    name = "Support"
    url = "/support/"
    weight = 6

[permalinks]
  posts = "/:year/:month/:slug/"
  pages = "/:filename/"

[params.blog.giscus]
  repo = "t3mujinpack/discussions"
  repo_id = "R_kgDOLn5X9Q"
  category = "Announcements"
  category_id = "DIC_kwDOLn5X9c4CeW7h"
  mapping = "og:title"
  reactions = true  
  lazy_loading = false